### ISSUE TITLE
Migrate Older Version of Theme?

### ISSUE THREAD

**Issue by chrismcintosh** [Whiteboard/launchframe#13]
### Issue
I'm getting an error anytime I run any gulp command i.e. 'gulp watch' 'gulp dist-css'
Do you have any tips for fixing this error or migrating to whats current in the master branch?

### Context
Hey guys kind of a strange request I'm aware, but I inherited a project using this theme. As far as I can tell no other developers have touched it. I've pulled it down to my local machine and run 'yarn' and followed all the steps in the readme.md

There is no documented version number of the theme but as far as I can tell it is sporting an older version of Launchframe theme.

In this version gulp is located in the assets folder, and all of the dependencies are using wildcards for their versions.

### Error
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/chris/Documents/Client Files/Delmarva Christian Schools/launchframe/assets/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/chris/Documents/Client Files/Delmarva Christian Schools/launchframe/assets/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/chris/Documents/Client Files/Delmarva Christian Schools/launchframe/assets/gulpfile.js:183:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

Here is a link to the repository - [https://github.com/chrismcintosh/DelmarvaChristianSchools](https://github.com/chrismcintosh/DelmarvaChristianSchools)

**Thanks for any help you might be able to offer!**

**Comment by phillphd** [comment]
@chrismcintosh Hello 👋 
It looks to be an error with using a newer version of gulp and outdated syntax in the gulpfile (https://github.com/gulpjs/undertaker/issues/54). So the gulpfile would need to be modified to work with Gulp 4.0. 
The gulpfile is building, linting and minifying the SCSS and JS and outputting the result into your assets/dist folder. You could also bypass Gulp and use a different program to accomplish that. Hopefully this answer gets you a little further down the road.

**Comment by chrismcintosh** [comment]
Thanks so much @phillphd !
